
name: Build PowerShellWeb
on: 
  push: 
  workflow_dispatch: 
jobs: 
  BuildPowerShellWeb: 
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps: 
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Use PSSVG Action
        uses: StartAutomating/PSSVG@main
        id: PSSVG

